### ISSUE TITLE
Approaches to running Node on Android

### ISSUE THREAD

**Issue by aschrijver** [dna2github/NodeBase#3]
Hi,

This is just a FYI, feel free to close.

I am not familiar to the native linking, compiling techniques in bringing Node to android, so find it hard to choose between options. To not waste your time, I first created a SO question with some of the approaches I found.

Here is the link: [Approaches to running NodeJS on Android](https://stackoverflow.com/q/45459909/8295283)

**Comment by dna2github** [comment]
Hi,

Thx for your question. I will do a brief answer in my view.

`1. Running V8 javascript engine on android which includes NodeJS`

pros:
- integrated with Java world; can get full control of code.

cons:
- a little hard to integrate with 3rd packages (need time to learn how).
- Need to learn about NodeJS and V8 things and also J2V8 docs (it consume long time).

`2. Compile NodeJS as a native library (using node-on-android)`

pros:
- focus on js dev and no need to consider android side.
- less learning time; similar to `Cordova` `phonegap` ....

cons:
- js app => apk is a black box.

`3. Running NodeJS on Android using Termux`

pros:
- flexible

cons:
- no gui

`4. Other interesting approaches`

Not familar with LiquidCore; build micro service especially from url, I think, is to resolve no direct available storage on iOS. `react-native-node` the Android part is based on NodeBase method and use the prebuilt binary. For NodeBase:

pros:
- similar to 3; difference is that it has its own gui to start/stop app.
- It can be a template for everything; for example, if would like to run django, you just need to replace node to python; rails, ruby...

cons:
- native process access problem; the process cannot inherit access from Android.
- happy toy happy open source not like a commercial app; need more design if want to distribute to customers

-------------------------

My idea to create NodeBase is that we can build sharable applications that can be shared in the same Wi-Fi. When host starts an app, it can be visited by near people. Then they can work and play together. For example, we play werewolf and when there is no judge, we will start the werewolf app to have a judge for the first round. We can also share files between devices via download/upload. For me, I can build what I want flexibly for example, I would like to make my Android as a machine learning runner; it can help me run machine learning programs at anytime (with node and python, thus in my another repo: https://github.com/dna2github/dns2oslab is focus on building binaries) to make use of phone running time.

For you, if wanna port your app in a short time, I recommend 2; if you have time and other resources, 1 is better. 3 if you just make a toy/demo. 4 `other` is always possible and just do your imagination to create works.

Best wishes,
Seven

**Comment by aschrijver** [comment]
Thanks a **LOT** for your extensive answer!! Very clarifying. 

Do you mind adding it to SO as well, or - if you are not on SO, I can copy the text and contribute to you?

**Comment by aschrijver** [comment]
PS I was trying to port `hypercore` to android for decentralized p2p apps.

**Comment by dna2github** [comment]
No, I don't mind however I am not on SO. you can copy the text if want.
Cool and enjoy your time :)

**Comment by aschrijver** [comment]
Thanks a bunch, man!! You too!!

**Comment by aschrijver** [comment]
The answer is there: https://stackoverflow.com/questions/45459909/compiling-nodejs-as-native-library-on-android/45468862#45468862
